# Xcode 9.1 on macOS 10.12
os: osx
osx_image: xcode9.1
language: objective-c
sudo: false

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    - THEOS=$PWD

before_install:
  # set up theos
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./extras/ci/macos-setup.sh; fi

script:
  # launch the test script
  - ./extras/ci/test-github-projects.sh
